// DEMO MODE: fictional sample data so the interface works without API keys.
// These comments were written for this demo. They are not real and are not about any real person.
const C = (n, platform, author, text) => ({
  id: `demo:${n}`,
  platform,
  author: platform === 'reddit' ? `u/${author}` : author,
  authorKey: `demo:${author}`,
  text,
  url: null,
  likes: 0,
  publishedAt: null,
  context: platform === 'reddit' ? 'r/sampledata: "Sample thread (fictional)"' : 'Sample comment (fictional)',
});

export const demoComments = [
  C(1, 'youtube', 'SampleUser_A', 'He comes across so warm here, genuinely kind to the interviewer.'),
  C(2, 'youtube', 'SampleUser_B', "That snide little remark at 4:10 was unnecessary. Kind of arrogant tbh."),
  C(3, 'youtube', 'SampleUser_C', 'Honestly funny. His dry humor goes over people\'s heads.'),
  C(4, 'youtube', 'SampleUser_D', 'Arrogant as always, but at least he is sincere about it.'),
  C(5, 'youtube', 'SampleUser_E', 'The constant smirking makes him look smug.'),
  C(6, 'youtube', 'SampleUser_F', 'His voice is so calm and soft-spoken, very soothing to listen to.'),
  C(7, 'youtube', 'SampleUser_G', 'Pretentious answers to simple questions lol'),
  C(8, 'youtube', 'SampleUser_H', 'He seems really sincere and thoughtful in this one.'),
  C(9, 'youtube', 'SampleUser_I', 'The album he talks about at 12:00 is overrated.'),
  C(10, 'youtube', 'SampleUser_J', 'Kind man. People misjudge him.'),
  C(11, 'youtube', 'SampleUser_K', 'He thinks he is better than everyone in the room.'),
  C(12, 'youtube', 'SampleUser_L', 'So funny when he deadpans the host.'),
  C(13, 'youtube', 'SampleUser_B', 'Rewatched it. Still arrogant.'),
  C(14, 'youtube', 'SampleUser_M', 'Great interview, the lighting was nice.'),
  C(15, 'youtube', 'SampleUser_N', 'His nasal voice is grating but I love the songs.'),
  C(16, 'reddit', 'sample_redditor_1', 'I met him once at a signing and he was warm and patient with everyone.'),
  C(17, 'reddit', 'sample_redditor_2', 'He can be snide in interviews but I think it is mostly shyness.'),
  C(18, 'reddit', 'sample_redditor_3', 'Pretentious? Sure. Talented? Also yes.'),
  C(19, 'reddit', 'sample_redditor_4', 'The way he fidgets with his rings the whole time, nervous energy.'),
  C(20, 'reddit', 'sample_redditor_5', 'Funny guy, very self-deprecating in person.'),
  C(21, 'reddit', 'sample_redditor_6', 'His politics are a mess, ignore those parts.'),
  C(22, 'reddit', 'sample_redditor_7', 'Sincere artist. That is rare.'),
];

const L = (n, term, category, polarity, quote) => ({ commentId: `demo:${n}`, term, category, polarity, quote });
export const demoLabels = [
  L(1, 'warm', 'personality', 'positive', 'He comes across so warm'),
  L(1, 'kind', 'personality', 'positive', 'genuinely kind to the interviewer'),
  L(2, 'snide', 'personality', 'negative', 'That snide little remark'),
  L(2, 'arrogant', 'personality', 'negative', 'Kind of arrogant'),
  L(3, 'funny', 'personality', 'positive', 'Honestly funny'),
  L(3, 'dry humor', 'personality', 'positive', 'His dry humor'),
  L(4, 'arrogant', 'personality', 'negative', 'Arrogant as always'),
  L(4, 'sincere', 'personality', 'mixed', 'he is sincere about it'),
  L(5, 'smirking', 'facial_expression', 'negative', 'The constant smirking'),
  L(5, 'smug', 'personality', 'negative', 'look smug'),
  L(6, 'calm', 'voice', 'positive', 'His voice is so calm'),
  L(6, 'soft-spoken', 'voice', 'positive', 'soft-spoken'),
  L(7, 'pretentious', 'personality', 'negative', 'Pretentious answers'),
  L(8, 'sincere', 'personality', 'positive', 'really sincere and thoughtful'),
  L(8, 'thoughtful', 'personality', 'positive', 'thoughtful'),
  L(9, 'overrated', 'music_or_work', 'negative', 'is overrated'),
  L(10, 'kind', 'personality', 'positive', 'Kind man'),
  L(11, 'condescending', 'personality', 'negative', 'He thinks he is better than everyone in the room'),
  L(12, 'funny', 'personality', 'positive', 'So funny when he deadpans the host'),
  L(12, 'deadpan', 'mannerisms', 'positive', 'deadpans the host'),
  L(13, 'arrogant', 'personality', 'negative', 'Still arrogant'),
  L(15, 'nasal', 'voice', 'negative', 'His nasal voice is grating'),
  L(16, 'warm', 'personality', 'positive', 'he was warm and patient with everyone'),
  L(16, 'patient', 'personality', 'positive', 'patient with everyone'),
  L(17, 'snide', 'personality', 'negative', 'He can be snide in interviews'),
  L(17, 'shy', 'personality', 'neutral', 'mostly shyness'),
  L(18, 'pretentious', 'personality', 'negative', 'Pretentious?'),
  L(18, 'talented', 'music_or_work', 'positive', 'Talented? Also yes.'),
  L(19, 'fidgety', 'mannerisms', 'negative', 'fidgets with his rings the whole time'),
  L(19, 'nervous', 'mannerisms', 'neutral', 'nervous energy'),
  L(20, 'funny', 'personality', 'positive', 'Funny guy'),
  L(20, 'self-deprecating', 'personality', 'positive', 'very self-deprecating'),
  L(21, 'messy politics', 'politics', 'negative', 'His politics are a mess'),
  L(22, 'sincere', 'personality', 'positive', 'Sincere artist'),
];
